apiVersion: v1
# configuration data for pods
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: karsajobs-ns
# Data: contain the configuration data
data:
  # Name of the configuration file what will be created
  mongo.conf: |
    storage: 
      dbpath: /data/db