apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret # Name of the Secret.
  namespace: karsajobs-ns # Namespace where the Secret will be created.
type: Opaque # Specifies the type of Secret as "Opaque."

data:
  # Using base64 encoding
  MONGO_ROOT_USERNAME: YWRtaW4= # Base64-encoded value for the MONGO_ROOT_USERNAME ("admin").
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # Base64-encoded value for the MONGO_ROOT_PASSWORD ("supersecretpassword").