apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv # Name of the PersistentVolume.
  namespace: karsajobs-ns # Namespace where the PersistentVolume will be created.
  labels:
    type: local # Labeling the PersistentVolume with "type: local."

spec:
  capacity:
    storage: 1Gi # Specifies the storage capacity of the PersistentVolume.
  accessModes:
    - ReadWriteOnce # Specifies that the volume can be mounted in read-write mode by a single node.
  persistentVolumeReclaimPolicy: Recycle # Specifies that the PersistentVolume should be recycled when released.
  storageClassName: manual # Specifies the storage class name for the PersistentVolume.
  hostPath:
    path: "/data/db" # Specifies the host path where the volume is physically located.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim # Name of the PersistentVolumeClaim.
  namespace: karsajobs-ns # Namespace where the PersistentVolumeClaim will be created.

spec:
  storageClassName: manual # Specifies the storage class name for the PersistentVolumeClaim.
  resources:
    requests:
      storage: 1Gi # Specifies the requested storage capacity for the PersistentVolumeClaim.
  accessModes:
    - ReadWriteOnce # Specifies that the volume can be mounted in read-write mode by a single node.
